// interface Breeds {
//   val1: string
//   val2: string
// }

export const catBreeds: Record<string, string>[] = [
  { val1: "abys", val2: "아비시니안" },
  { val1: "aege", val2: "아에지안" },
  { val1: "abob", val2: "아보시니안" },
  { val1: "acur", val2: "아쿠르" },
  { val1: "asho", val2: "아쇼" },
  { val1: "awir", val2: "아워" },
  { val1: "amau", val2: "아마우" },
  { val1: "amis", val2: "아미스" },
  { val1: "bali", val2: "발리" },
  { val1: "bamb", val2: "밤브" },
  { val1: "beng", val2: "벵골" },
  { val1: "birm", val2: "버먼" },
  { val1: "bomb", val2: "봄브" },
  { val1: "bslo", val2: "브리티시 숏헤어" },
  { val1: "bsho", val2: "브리티시 숏헤어" },
  { val1: "bure", val2: "부르" },
  { val1: "buri", val2: "부리" },
  { val1: "cspa", val2: "코르디페리" },
  { val1: "ctif", val2: "칠라티프" },
  { val1: "char", val2: "샤르" },
  { val1: "chau", val2: "샤우" },
  { val1: "chee", val2: "치에" },
  { val1: "csho", val2: "치솟" },
  { val1: "crex", val2: "크렉스" },
  { val1: "cymr", val2: "시미르" },
  { val1: "cypr", val2: "사이프러스" },
  { val1: "drex", val2: "드렉스" },
  { val1: "dons", val2: "도스" },
  { val1: "lihu", val2: "리후" },
  { val1: "emau", val2: "에마우" },
  { val1: "ebur", val2: "에부르" },
  { val1: "esho", val2: "에쇼" },
  { val1: "hbro", val2: "히브로" },
  { val1: "hima", val2: "히마" },
  { val1: "jbob", val2: "제이봅" },
  { val1: "java", val2: "자바" },
  { val1: "khao", val2: "카오" },
  { val1: "kora", val2: "코라" },
  { val1: "kuri", val2: "쿠리" },
  { val1: "lape", val2: "라페" },
  { val1: "mcoo", val2: "마코" },
  { val1: "mala", val2: "말라" },
  { val1: "manx", val2: "맨크스" },
  { val1: "munc", val2: "먼크스" },
  { val1: "nebe", val2: "네베" },
  { val1: "norw", val2: "노르웨이" },
  { val1: "ocic", val2: "오시캣" },
  { val1: "orie", val2: "오리엔탈" },
  { val1: "pers", val2: "페르시안" },
  { val1: "pixi", val2: "픽시" },
  { val1: "raga", val2: "라가" },
  { val1: "ragd", val2: "래그돌" },
  { val1: "rblu", val2: "로얄 블루" },
  { val1: "sava", val2: "사바" },
  { val1: "sfol", val2: "숲의 고양이" },
  { val1: "srex", val2: "수컷 고양이" },
  { val1: "siam", val2: "샴" },
  { val1: "sibe", val2: "시베리안" },
  { val1: "sing", val2: "싱가포르" },
  { val1: "snow", val2: "스노우" },
  { val1: "soma", val2: "소마" },
  { val1: "sphy", val2: "스피니스" },
  { val1: "tonk", val2: "톤킨" },
  { val1: "toyg", val2: "토이" },
  { val1: "tang", val2: "탕" },
  { val1: "tvan", val2: "트리반" },
  { val1: "ycho", val2: "요코" },
]
